name: $(Year:yy).$(minorVersion)

variables:
  minorVersion: $[counter(variables['Year:yy'], 1)]
  buildConfiguration: Release 
  appName: Iface.Oik.EventDispatcher
  archiveName: $(appName).$(Build.BuildNumber)


trigger:
- master

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: 'src/**/*.csproj'
    arguments: '-c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: 'tests/**/*.csproj'
    arguments: '-c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    projects: 'src/**/*.csproj'
    publishWebProjects: false
    arguments: '-c $(BuildConfiguration) -r win-x64 --self-contained false -o $(Build.ArtifactStagingDirectory)/bin'
    zipAfterPublish: false
    modifyOutputPath: false
    
- task: CopyFiles@2
  displayName: Publish
  inputs:
    contents: 'sample_configs/*.json'
    targetFolder: $(Build.ArtifactStagingDirectory)/sample_configs
    flattenFolders: true
    
- script: mkdir $(Build.ArtifactStagingDirectory)/configs
  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: $(Build.ArtifactStagingDirectory)
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(archiveName).zip
    
- publish: $(Build.ArtifactStagingDirectory)/$(archiveName).zip
  artifact: $(appName)
  
- task: GithubRelease@0
  inputs:
    gitHubConnection: GitHub
    repositoryName: $(Build.Repository.Name)
    tagSource: manual
    tag: $(Build.BuildNumber)
    assets: $(Build.ArtifactStagingDirectory)/$(archiveName).zip